name:                tagit
version:             0.1.0.0

default-extensions:
- PackageImports
- LambdaCase

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - filepath
  - unix
  - unix-bytestring
  - HFuse

ghc-options:
    - -threaded
    - -Wall
    - -Wcompat
    - -Werror
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wmonomorphism-restriction
    - -Wnoncanonical-monad-instances
    - -Wnoncanonical-monadfail-instances
    - -j8

executables:
  tagit:
    source-dirs:      src
    main:             Main.hs
