name:                tagit
version:             0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - unix
  - HFuse

executables:
  tagit:
    source-dirs:      src
    main:             Main.hs
